version: '3.1'

# https://docs.microsoft.com/pl-pl/azure/mysql/howto-configure-ssl

services:
  adminer:
    image: adminer:4.8.1
    # image: dockette/adminer:latest
    # image: dehy/adminer:latest
    container_name: adminer
    restart: always
    environment:
      ADMINER_DESIGN: rmsoft
      DB_SSL_CA: '/certs/ca.pem'
    volumes:
      - ./login-azure-ssl.php:/var/www/html/plugins-enabled/login-azure-ssl.php
      - ${DB_SSL_CA}:/certs/ca.pem
      - ./php-ini-overrides.ini:/usr/local/etc/php/conf.d/zz-php-ini-overrides.ini
    ports:
      - 18080:8080
    networks:
      galderma:
      dmo:

networks:
  galderma:
    name: galderma
  dmo:
    name: dmo
