version: '3.1'

# https://docs.microsoft.com/pl-pl/azure/mysql/howto-configure-ssl

services:
  adminer:
    image: adminer:4.8.0
    # image: dockette/adminer:latest
    # image: dehy/adminer:latest
    container_name: adminer
    restart: always
    environment:
      ADMINER_DESIGN: flat
      DB_SSL_CA: '/certs/ca.pem'
      MEMORY: 512M
      UPLOAD: 1024M
    volumes:
      - ./login-azure-ssl.php:/var/www/html/plugins-enabled/login-azure-ssl.php
      - ${DB_SSL_CA}:/certs/ca.pem
    ports:
      - 18080:8080
